init hw03
kirgizz/go_otus pull request #8
Opened 2020-12-22 16:19 UTC by kirgizz

2020-12-22 20:11 UTC, balabanovds requested changes
Неплохо, лаконично.

Можно улучшить и есть критические места.
Возвращаю на проверку.

Также нужно написать тесты, без них работа не проходит минимальную оценку.

Будут вопросы - доступен в Slack.

Успехов!

<https://otus.ru/teacher-lk/homework/149038/9017/>

2020-12-22 20:11 UTC, balabanovds commented on hw03_frequency_analysis/hw03_frequency_analysis/top.go
> +	r := regexp.MustCompile(`\n|\s|\t|\z`)
`regexp` - довольно тяжелая функция.  
Тяжелые функции стоит выносить в конструктор, чтобы вызывались один раз.
Сейчас это не критично, но стоит помнить на будущее.

Также отмечу, что здесь более оптимально можно использовать `strings.Fields`

2020-12-22 20:11 UTC, balabanovds commented on hw03_frequency_analysis/hw03_frequency_analysis/top.go
> +	entryes := map[string]int{}
обычно для инициализации мапы используют make(map[string]int), как-то лучше читается, но это дело вкуса

2020-12-22 20:11 UTC, balabanovds commented on hw03_frequency_analysis/hw03_frequency_analysis/top.go
> +		if word == "" {
если использовать `strings.Fields` эту проверку можно опустить

2020-12-22 20:11 UTC, balabanovds commented on hw03_frequency_analysis/main.go
> +package main
зачем вынесли в отдельный пакет? 
Вы пишете просто либу и тесты на нее.
Бинарь тут не нужен

2020-12-22 20:11 UTC, balabanovds commented on hw03_frequency_analysis/hw03_frequency_analysis/top.go
> +	return sortedWords[:topWordsCount]
здесь Вы словите панику, если количество слов меньше topWordsCount

2020-12-26 15:07 UTC, kirgizz commented on hw03_frequency_analysis/hw03_frequency_analysis/top.go
> +	r := regexp.MustCompile(`\n|\s|\t|\z`)
да, не нашел сраз методе strings.fields, поменял код на использование этой функции

2020-12-26 15:08 UTC, kirgizz commented on hw03_frequency_analysis/hw03_frequency_analysis/top.go
> +	r := regexp.MustCompile(`\n|\s|\t|\z`)
про конструктор кстати не совсем понял, у меня же тут нет структур никаких

2020-12-26 15:08 UTC, kirgizz commented on hw03_frequency_analysis/hw03_frequency_analysis/top.go
> +		if word == "" {
поменял

2020-12-26 15:08 UTC, kirgizz commented on hw03_frequency_analysis/main.go
> +package main
тут я маин заинитил для отладки в основном, чтобы проверять что у меня по ходу получалось. если критично могу конечно убрать

2020-12-26 15:09 UTC, kirgizz commented on hw03_frequency_analysis/hw03_frequency_analysis/top.go
> +	return sortedWords[:topWordsCount]
добавил проверку

2020-12-26 15:46 UTC, balabanovds requested changes
Уже лучше, но нужно доделать. 
Отписал в комментарии

2020-12-26 15:46 UTC, balabanovds commented on hw03_frequency_analysis/hw03_frequency_analysis/top_test.go
> +		require.Len(t, Top10(text), topWordsCount)
тут Вы просто убедились что текст реально содержит длину равную topWordsCount, а не то что количество слов меньше чем ожидается (topWordsCount)

И вообще в задании нигде не сказано, что если текст содержит меньше topWordsCount то эти слова нужно игнорировать.

У Вас строка например "a s d" вернет nil, хотя я бы ожидал "a d s"

2020-12-28 10:23 UTC, kirgizz commented on hw03_frequency_analysis/hw03_frequency_analysis/top_test.go
> +		require.Len(t, Top10(text), topWordsCount)
ну, нигде и не сказано, что нужно возвращать список ) решил сделать как можно проще. поменял на возврат списка

2020-12-28 10:24 UTC, kirgizz commented on hw03_frequency_analysis/hw03_frequency_analysis/top_test.go
> +		require.Len(t, Top10(text), topWordsCount)
ммм... не совсем понял комментарий

2020-12-28 16:18 UTC, balabanovds commented on hw03_frequency_analysis/main.go
> +package main
проще дебажить прямо конкретный тест, любой IDE умеет

2020-12-28 16:19 UTC, balabanovds commented on hw03_frequency_analysis/hw03_frequency_analysis/top.go
> +	r := regexp.MustCompile(`\n|\s|\t|\z`)
про конструктор - это на будущее

2020-12-28 16:25 UTC, balabanovds commented on hw03_frequency_analysis/hw03_frequency_analysis/top_test.go
> +		require.Len(t, Top10(text), topWordsCount)
@kirgizz я здесь имелл ввиду слудующее:
у Вас название теста "words count less than expected", что читается как "количество слов меньше чем ожидается"
Вы проверяете что Top10(text) возвращает слайс с длиной topWordsCount, что на самом деле проверятся что "количество слов равное тому что ожидается".

2020-12-28 19:19 UTC, balabanovds commented on hw03_frequency_analysis/hw03_frequency_analysis/top_test.go
> +		require.Len(t, Top10(text), topWordsCount)
Это незначительное замечание, больше пожелание на будущее

2020-12-28 19:25 UTC, balabanovds approved these changes
Хорошо. Работа принимается.

На будущее - пишите больше тестов, стараясь учесть все пограничные случаи

Успехов!

https://otus.ru/teacher-lk/homework/149038/9017/

2021-01-02 13:32 UTC, kirgizz commented
done

2021-01-02 13:32 UTC, merged